import { Lesson, Difficulty } from '../../../../../types';
import { grammar } from './grammar';
import { vocabulary, phrasalVerbs, compoundWords, functionalChunks } from './vocabulary';

export const lesson01: Lesson = {
  id: "we1",
  title: "Describing the Workplace",
  level: Difficulty.A1,
  description: "Learn to describe workplaces and office environments using 'there is/are' and prepositions of place. Essential vocabulary for discussing office layouts, remote work, and workspace arrangements in a professional setting.",
  didYouKnow:
    "In software, we also describe a 'workspace'. For example, in an IDE like VS Code, your 'workspace' contains all the files and folders for your project, along with your personal settings and configurations. Many developers also 'make a request' for new features or 'set up a desk' in digital project boards, mirroring physical office tasks.",

  grammar,
  vocabulary,
  phrasalVerbs,
  compoundWords,
  functionalChunks,

  scenario:
    "Describe your workspace to a new team member and make a simple request for new equipment.",
  speaking:
    "Role-play: You are a new employee. Describe your desk to your manager using prepositions (e.g., 'There is a laptop on my desk'). Then, ask for a second monitor.",
  speakingPracticeMode: "conversation",
  readingActivity: {
    title: "Reading: Virtual Office Tour",
    text: "Welcome to your new workspace! Your desk is **next to** the big window. **On** your desk, **there is** a new laptop and one monitor. **There are** some notebooks and pens **in** the top drawer. The team's meeting room is **at** the end of the hall. If you need anything, just ask!",
    comprehensionQuestions: [
      {
        question: "What is on the desk?",
        answer: "There is a new laptop and one monitor.",
      },
      {
        question: "Where is the meeting room located?",
        answer: "The meeting room is at the end of the hall.",
      },
      {
        question: "What is in the top drawer?",
        answer: "There are some notebooks and pens in the top drawer.",
      },
    ],
  },
  listeningActivity: {
    title: "Listening: Office Tour",
    audioSrc: "", // Will be generated by Gemini TTS when needed
    transcript: "Welcome to TechCorp offices! There is a coffee machine next to reception. There are meeting rooms along the main hallway. Your desk is in the corner with two monitors on it. Please ask if you need anything - we're happy to help new team members settle in.",
    comprehensionQuestions: [
      {
        question: "What is next to reception?",
        answer: "There is a coffee machine next to reception.",
      },
      {
        question: "Where are the meeting rooms?",
        answer: "There are meeting rooms along the main hallway.",
      },
      {
        question: "What is there on the desk?",
        answer: "There are two monitors on the desk.",
      },
    ],
  },
  pronunciationClinic: {
    title: "Pronunciation Clinic: Workplace Vocabulary",
    explanation: "Master key workplace terms for clear communication in professional settings. These words are commonly used in IT and tech environments.",
    examples: [
      {
        term: "workspace",
        phonetic: "/ˈwɜːrkˈspeɪs/",
        tip: "Two syllables with primary stress on 'work'. Don't stress the 's' - it's pronounced like 'works' with a silent 'e'.",
      },
      {
        term: "meeting room",
        phonetic: "/ˈmiːtɪŋ ruːm/",
        tip: "Stress on 'meet' (not 'ing'). Room is pronounced 'room' (not 'ruhm'). The 't' is soft.",
      },
      {
        term: "coworking space",
        phonetic: "/ˈkoʊˈwɜːrkɪŋ speɪs/",
        tip: "Three syllables: 'co-work-ing space'. Stress on 'work'. The 'cow' part rhymes with 'now'.",
      },
      {
        term: "set up",
        phonetic: "/sɛt ʌp/",
        tip: "Short 'e' sound in 'set', weak vowel 'uh' in 'up'. As a phrasal verb, stress can shift depending on usage.",
      },
      {
        term: "remote",
        phonetic: "/rɪˈmoʊt/",
        tip: "Three syllables: 're-mote'. Primary stress on second syllable. The 'o' is long, like 'oh'.",
      },
    ]
  },
  globalAccentLab: [
    {
      accent: "American English (California)",
      speakerBio: "Jenna, Office Manager from Los Angeles",
      audioSrc: "https://storage.googleapis.com/aistudio-public/prompts/media/tech-english-pro/a1_m03_l01_accent_us.mp3",
      transcript: "Welcome! So, this is your new desk. There's a monitor and a laptop for you. There are meeting rooms down the hall if you need one.",
    },
    {
      accent: "British English (London)",
      speakerBio: "Arthur, Team Lead from London",
      audioSrc: "https://storage.googleapis.com/aistudio-public/prompts/media/tech-english-pro/a1_m03_l01_accent_uk.mp3",
      transcript: "Right, so this is the office. Your desk is over there, next to the window. There is a spare monitor you can use. There are also some quiet rooms on this floor.",
    },
    {
      accent: "German English (Berlin)",
      speakerBio: "Frank, IT Support from Berlin",
      audioSrc: "https://storage.googleapis.com/aistudio-public/prompts/media/tech-english-pro/a1_m03_l01_accent_de.mp3",
      transcript: "Hello. In this office, there is a kitchen on the left. On your desk, there is one monitor. If you need a second one, please make a ticket.",
    },
  ],
  rolePlay: {
    title: "The Office Tour",
    objective: "Show a new colleague around your workplace and describe the office layout using 'there is/are' and prepositions of place.",
    aiPersona: "Sarah, New Frontend Developer",
    initialMessage: "Hi! Thanks for showing me around. Can you tell me where everything is? I'm a bit lost!",
  }
};
